# Generated by Django 6.0.2 on 2026-02-14 18:20

import MainWorkerfy.paths
import MainWorkerfy.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initials', models.CharField(default='N/A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Trade Categories',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWorkerfy.city')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring'), ('contract', 'Contract')], max_length=20)),
                ('description', models.TextField()),
                ('area', models.CharField(blank=True, max_length=255)),
                ('work_environment', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('residential', 'Residential'), ('industrial', 'Industrial')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('urgency_level', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('normal', 'Normal')], max_length=10)),
                ('budget_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('negotiable', 'Negotiable')], max_length=20)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('materials_provided', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills for the job')),
                ('contact_method', models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('call', 'Call'), ('text', 'Text')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWorkerfy.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWorkerfy.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='MainWorkerfy.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='MainWorkerfy.country')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWorkerfy.region'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('other_names', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(blank=True, help_text='Username for login', max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('contact_number', models.CharField(blank=True, help_text='Phone number for client contact', max_length=15)),
                ('contact_number2', models.CharField(blank=True, help_text='Secondary phone number (Whatsapp, etc.)', max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sub_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sub_location', to='MainWorkerfy.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('work_areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_areas', to='MainWorkerfy.area')),
                ('base_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_base_location', to='MainWorkerfy.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWorkerfy.region'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='trade_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWorkerfy.tradecategory'),
        ),
        migrations.CreateModel(
            name='TradeSkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='MainWorkerfy.tradecategory')),
            ],
            options={
                'verbose_name': 'Trade Skill Tag',
                'verbose_name_plural': 'Trade Skill Tags',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TradeSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='MainWorkerfy.tradecategory')),
            ],
            options={
                'verbose_name_plural': 'Trade Specialties',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TradespersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('other_names', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='Short bio or introduction')),
                ('tagline', models.CharField(blank=True, help_text='A catchy tagline for your profile', max_length=100)),
                ('contact_number', models.CharField(blank=True, help_text='Phone number for client contact', max_length=15)),
                ('contact_number2', models.CharField(blank=True, help_text='Secondary phone number (Whatsapp, etc.)', max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links (e.g. Facebook, Instagram)')),
                ('website', models.URLField(blank=True, help_text='Personal or business website URL')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is this profile active?')),
                ('is_verified', models.BooleanField(default=False, help_text='Is this tradesperson verified?')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('working_areas', models.JSONField(blank=True, default=dict, help_text='Areas tradespeople can service')),
                ('availability_status', models.CharField(choices=[('Available Now', 'Available Now'), ('Urgent', 'Urgent'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=50)),
                ('education_schools', models.JSONField(blank=True, default=dict, help_text='List of schools attended')),
                ('other_skills', models.JSONField(blank=True, default=list, help_text='Other skills not covered by tags')),
                ('rate_charged', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly or project rate charged by the tradesperson', max_digits=10, null=True)),
                ('base_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople_base', to='MainWorkerfy.region')),
                ('skills', models.ManyToManyField(blank=True, related_name='tradespeople_skills', to='MainWorkerfy.tradeskilltag')),
                ('sub_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople_sub', to='MainWorkerfy.city')),
                ('trade_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople_category', to='MainWorkerfy.tradecategory')),
                ('trade_specialties', models.ManyToManyField(blank=True, related_name='tradespeople_specialty', to='MainWorkerfy.tradespecialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tradesperson_profile', to=settings.AUTH_USER_MODEL)),
                ('work_areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople_work_areas', to='MainWorkerfy.area')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=MainWorkerfy.paths.portfolio_image_upload_path, validators=[MainWorkerfy.validators.validate_certificate_file])),
                ('video', models.FileField(blank=True, null=True, upload_to=MainWorkerfy.paths.portfolio_video_upload_path, validators=[MainWorkerfy.validators.validate_video_size, MainWorkerfy.validators.validate_video_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='MainWorkerfy.tradespersonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(help_text='Upload PDF or image file (max 5MB)', upload_to='certificates/', validators=[MainWorkerfy.validators.validate_certificate_file])),
                ('contact_person', models.CharField(blank=True, help_text='Person to contact for verification', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Additional instructions or context for verification')),
                ('verified', models.BooleanField(default=False)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='MainWorkerfy.tradespersonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='e.g. Admin, Course, Test, etc.', max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWorkerfy.badge')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='MainWorkerfy.tradespersonprofile')),
            ],
            options={
                'unique_together': {('tradesperson', 'badge')},
            },
        ),
    ]
