# Generated by Django 5.1.2 on 2025-08-12 20:12

import MainWorkerfy.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(help_text='Upload PDF or image file (max 5MB)', upload_to='certificates/', validators=[MainWorkerfy.validators.validate_certificate_file])),
                ('contact_person', models.CharField(blank=True, help_text='Person to contact for verification', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Additional instructions or context for verification')),
                ('verified', models.BooleanField(default=False)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='MainWorkerfy.tradespersonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='e.g. Admin, Course, Test, etc.', max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWorkerfy.badge')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='MainWorkerfy.tradespersonprofile')),
            ],
            options={
                'unique_together': {('tradesperson', 'badge')},
            },
        ),
    ]
