# Generated by Django 5.1.2 on 2025-08-13 05:23

import MainWorkerfy.paths
import MainWorkerfy.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0002_badge_certificate_earnedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradespersonprofile',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Urgent', 'Urgent'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople', to='MainWorkerfy.region'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or introduction'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone number for client contact', max_length=15),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='contact_number2',
            field=models.CharField(blank=True, help_text='Secondary phone number (Whatsapp, etc.)', max_length=15),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='education_schools',
            field=models.JSONField(blank=True, default=list, help_text='List of schools attended'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this profile active?'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Is this tradesperson verified?'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='other_names',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links (e.g. Facebook, Instagram)'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople', to='MainWorkerfy.city'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='username',
            field=models.CharField(blank=True, help_text='Username for login', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or business website URL'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='working_days_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Working hours for each day of the week'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=MainWorkerfy.paths.portfolio_image_upload_path, validators=[MainWorkerfy.validators.validate_certificate_file])),
                ('video', models.FileField(blank=True, null=True, upload_to=MainWorkerfy.paths.portfolio_video_upload_path, validators=[MainWorkerfy.validators.validate_video_size, MainWorkerfy.validators.validate_video_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='MainWorkerfy.tradespersonprofile')),
            ],
        ),
    ]
