# Generated by Django 5.1.2 on 2025-08-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0003_tradespersonprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='trade_specialties',
            field=models.ManyToManyField(blank=True, null=True, related_name='tradespeople', to='MainWorkerfy.tradespecialty'),
        ),
    ]
