# Generated by Django 5.1.2 on 2025-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0004_alter_tradespersonprofile_trade_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='work_areas',
            field=models.ManyToManyField(blank=True, null=True, related_name='tradespeople', to='MainWorkerfy.area'),
        ),
    ]
