# Generated by Django 5.1.2 on 2025-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0005_alter_tradespersonprofile_work_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='trade_specialties',
            field=models.ManyToManyField(blank=True, related_name='tradespeople', to='MainWorkerfy.tradespecialty'),
        ),
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='work_areas',
            field=models.ManyToManyField(blank=True, related_name='tradespeople', to='MainWorkerfy.area'),
        ),
    ]
