# Generated by Django 5.1.2 on 2025-08-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0006_alter_tradespersonprofile_trade_specialties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradespersonprofile',
            name='working_days_hours',
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='working_areas',
            field=models.JSONField(blank=True, default=dict, help_text='Areas tradespeople can service'),
        ),
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='education_schools',
            field=models.JSONField(blank=True, default=dict, help_text='List of schools attended'),
        ),
        migrations.RemoveField(
            model_name='tradespersonprofile',
            name='work_areas',
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='work_areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradespeople', to='MainWorkerfy.area'),
        ),
    ]
