# Generated by Django 5.1.2 on 2025-09-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0007_remove_tradespersonprofile_working_days_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='username',
            field=models.CharField(blank=True, help_text='Username for login', max_length=150),
        ),
    ]
