# Generated by Django 5.1.2 on 2025-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0008_alter_tradespersonprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='other_skills',
            field=models.JSONField(blank=True, default=dict, help_text='Other skills not covered by tags'),
        ),
        migrations.AddField(
            model_name='tradespersonprofile',
            name='rate_charged',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly or project rate charged by the tradesperson', max_digits=10, null=True),
        ),
    ]
