# Generated by Django 5.1.2 on 2025-09-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0009_country_tradespersonprofile_other_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='MainWorkerfy.country'),
            preserve_default=False,
        ),
    ]
