# Generated by Django 5.1.2 on 2025-09-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWorkerfy', '0011_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradespersonprofile',
            name='other_skills',
            field=models.JSONField(blank=True, default=list, help_text='Other skills not covered by tags'),
        ),
    ]
