# Generated by Django 5.1.2 on 2024-10-25 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='Tradesperson',
            fields=[
                ('tradesperson_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('extra_skills', models.TextField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('work_hours', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('FREELANCE_CONTRACTS', 'Freelance contracts')], default='Full time', max_length=255)),
                ('service_range', models.CharField(max_length=255)),
                ('past_jobs', models.TextField(blank=True, null=True)),
                ('rate_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(max_length=255)),
                ('availability_status', models.CharField(choices=[('URGENT', 'Urgent'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=255)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('NOT VERIFIED', 'Not verified')], default='Not verified', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tradesperson',
                'verbose_name_plural': 'Tradespeople',
            },
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('trades_id', models.AutoField(primary_key=True, serialize=False)),
                ('trades_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Trade Type',
                'verbose_name_plural': 'Trade Types',
                'ordering': ['trades_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerfyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('tradesperson', 'Tradesperson')], max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workerfy User',
                'verbose_name_plural': 'Workerfy Users',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_start', models.DateField()),
                ('job_end', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], max_length=50)),
                ('application_deadline', models.DateField()),
                ('skills_required', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_start', models.DateTimeField(blank=True, null=True)),
                ('booking_end', models.DateTimeField(blank=True, null=True)),
                ('booking_description', models.TextField()),
                ('booking_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('client_message', models.TextField(blank=True, null=True)),
                ('tradesperson_response', models.TextField(blank=True, null=True)),
                ('rate_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
                ('features', models.ManyToManyField(to='Discover.feature')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Discover.jobposting')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_start', models.DateTimeField()),
                ('service_end', models.DateTimeField(blank=True, null=True)),
                ('flag', models.CharField(choices=[('Green', 'GREEN'), ('Red', 'RED')], default='Green', max_length=50)),
                ('service_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Discover.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-service_start'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment')], max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('upfront_payment', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.service')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.service')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispute_reason', models.TextField()),
                ('dispute_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('initiator', models.CharField(choices=[('client', 'Client'), ('tradesperson', 'Tradesperson')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('evidence_files', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.service')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, max_length=500, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.jobposting')),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='TradespersonCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tradesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.tradesperson')),
                ('trade_types', models.ManyToManyField(to='Discover.tradetype')),
            ],
            options={
                'verbose_name': 'Tradesperson Category',
                'verbose_name_plural': 'Tradesperson Categories',
            },
        ),
        migrations.AddField(
            model_name='tradesperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Discover.workerfyuser'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discover.workerfyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Discover.workerfyuser'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Discover.workerfyuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
