# Generated by Django 5.1.2 on 2024-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerfyuser',
            old_name='is_verified',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='workerfyuser',
            name='password',
            field=models.CharField(default='user123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerfyuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workerfyuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='workerfyuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('tradesperson', 'Tradesperson'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workerfyuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
