# Generated by Django 5.1.2 on 2024-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0002_rename_is_verified_workerfyuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tradesperson',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='No name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradesperson',
            name='last_name',
            field=models.CharField(default='no name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradesperson',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
