# Generated by Django 5.1.2 on 2024-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0003_rename_full_name_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesperson',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='extra_skills',
            field=models.CharField(choices=[('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Roofer', 'Roofer'), ('Painter', 'Painter'), ('Drywall', 'Drywall'), ('Glazier', 'Glazier'), ('Tiler', 'Tiler'), ('Ironworker', 'Iron worker or Steel Worker'), ('Welder', 'Welder'), ('HVAC_Technician', 'HVAC Technician'), ('Concrete_Worker', 'Concrete Worker'), ('Refrigeration_Technician', 'Refrigeration Technician'), ('Landscaper/Gardener', 'Landscaper/Gardener'), ('Locksmith', 'Locksmith'), ('Pest_Control_Technician', 'Pest Control Technician'), ('Cleaning_Technician', 'Cleaning Technician'), ('Gas_Fitter', 'Gas Fitter'), ('Septic_Tank_Installer/Repairer', 'Septic Tank Installer/Repairer'), ('Appliance_Repair_Technician', 'Appliance Repair Technician'), ('Solar_Panel_Installer', 'Solar Panel Installer'), ('Green_Energy_Technician', 'Green Energy Technician'), ('Smart_Home_Technician', 'Smart Home Technician'), ('Waterproofing_Specialist', 'Waterproofing Specialist'), ('General_Contractor', 'General Contractor'), ('Handyman', 'Handyman'), ('Scaffolder', 'Scaffolder'), ('Labourer', 'Labourer'), ('Elevator_Installer_Repairer', 'Elevator Installer/Repairer'), ('Auto_Mechanic', 'Auto Mechanic'), ('Heavy_Equipment_Operator', 'Heavy Equipment Operator'), ('Sheet_Metal_Worker', 'Sheet Metal Worker'), ('Industrial_Electrician', 'Industrial Electrician'), ('Pipefitter', 'Pipefitter/Steamfitter')], default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='location',
            field=models.CharField(choices=[('Greater_Accra', 'Greater Accra'), ('Volta', 'Volta Region'), ('Ashanti', 'Ashanti Region'), ('Western_North', 'Western North Region'), ('Western', 'Western Region'), ('Central', 'Central Region'), ('Upper_East', 'Upper East Region'), ('Savannah', 'Savannah Region'), ('North_East', 'North East Region'), ('Bono', 'Bono Region'), ('Ahafo', 'Ahafo Region'), ('Bono_East', 'Bono East Region'), ('Upper_West', 'Upper West Region'), ('Nortern', 'Nortern Region'), ('Oti', 'Oti Region'), ('Eastern', 'Eastern Region')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='past_jobs',
            field=models.ImageField(blank=True, null=True, upload_to='past_jobs/'),
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='specialization',
            field=models.CharField(choices=[('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Roofer', 'Roofer'), ('Painter', 'Painter'), ('Drywall', 'Drywall'), ('Glazier', 'Glazier'), ('Tiler', 'Tiler'), ('Ironworker', 'Iron worker or Steel Worker'), ('Welder', 'Welder'), ('HVAC_Technician', 'HVAC Technician'), ('Concrete_Worker', 'Concrete Worker'), ('Refrigeration_Technician', 'Refrigeration Technician'), ('Landscaper/Gardener', 'Landscaper/Gardener'), ('Locksmith', 'Locksmith'), ('Pest_Control_Technician', 'Pest Control Technician'), ('Cleaning_Technician', 'Cleaning Technician'), ('Gas_Fitter', 'Gas Fitter'), ('Septic_Tank_Installer/Repairer', 'Septic Tank Installer/Repairer'), ('Appliance_Repair_Technician', 'Appliance Repair Technician'), ('Solar_Panel_Installer', 'Solar Panel Installer'), ('Green_Energy_Technician', 'Green Energy Technician'), ('Smart_Home_Technician', 'Smart Home Technician'), ('Waterproofing_Specialist', 'Waterproofing Specialist'), ('General_Contractor', 'General Contractor'), ('Handyman', 'Handyman'), ('Scaffolder', 'Scaffolder'), ('Labourer', 'Labourer'), ('Elevator_Installer_Repairer', 'Elevator Installer/Repairer'), ('Auto_Mechanic', 'Auto Mechanic'), ('Heavy_Equipment_Operator', 'Heavy Equipment Operator'), ('Sheet_Metal_Worker', 'Sheet Metal Worker'), ('Industrial_Electrician', 'Industrial Electrician'), ('Pipefitter', 'Pipefitter/Steamfitter')], max_length=50),
        ),
    ]
