# Generated by Django 5.1.2 on 2024-11-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0004_alter_tradesperson_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesperson',
            name='trades_type',
            field=models.CharField(choices=[('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Roofer', 'Roofer'), ('Painter', 'Painter'), ('Drywall', 'Drywall'), ('Glazier', 'Glazier'), ('Tiler', 'Tiler'), ('Ironworker', 'Iron worker or Steel Worker'), ('Welder', 'Welder'), ('HVAC_Technician', 'HVAC Technician'), ('Concrete_Worker', 'Concrete Worker'), ('Refrigeration_Technician', 'Refrigeration Technician'), ('Landscaper/Gardener', 'Landscaper/Gardener'), ('Locksmith', 'Locksmith'), ('Pest_Control_Technician', 'Pest Control Technician'), ('Cleaning_Technician', 'Cleaning Technician'), ('Gas_Fitter', 'Gas Fitter'), ('Septic_Tank_Installer/Repairer', 'Septic Tank Installer/Repairer'), ('Appliance_Repair_Technician', 'Appliance Repair Technician'), ('Solar_Panel_Installer', 'Solar Panel Installer'), ('Green_Energy_Technician', 'Green Energy Technician'), ('Smart_Home_Technician', 'Smart Home Technician'), ('Waterproofing_Specialist', 'Waterproofing Specialist'), ('General_Contractor', 'General Contractor'), ('Handyman', 'Handyman'), ('Scaffolder', 'Scaffolder'), ('Labourer', 'Labourer'), ('Elevator_Installer_Repairer', 'Elevator Installer/Repairer'), ('Auto_Mechanic', 'Auto Mechanic'), ('Heavy_Equipment_Operator', 'Heavy Equipment Operator'), ('Sheet_Metal_Worker', 'Sheet Metal Worker'), ('Industrial_Electrician', 'Industrial Electrician'), ('Pipefitter', 'Pipefitter/Steamfitter')], default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
    ]
