# Generated by Django 5.1.2 on 2024-11-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0006_alter_tradesperson_profile_picture_pastworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesperson',
            name='past_jobs',
        ),
        migrations.AlterField(
            model_name='tradesperson',
            name='service_range',
            field=models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], max_length=255),
        ),
    ]
