# Generated by Django 5.1.2 on 2024-11-06 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0007_remove_tradesperson_past_jobs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastworkimage',
            options={'verbose_name': 'Past Work Image', 'verbose_name_plural': 'Past Work Images'},
        ),
        migrations.AddField(
            model_name='workerfyuser',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='workerfyuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
