# Generated by Django 5.1.2 on 2025-07-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0008_alter_pastworkimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerfyuser',
            name='username',
        ),
    ]
